export const TEAM_CRESTS: Record<string, string> = {
	"1. FC Dynamo Dresden": "https://tmssl.akamaized.net//images/wappen/small/129.png",
	"1. FC Kaiserslautern": "https://tmssl.akamaized.net//images/wappen/small/2.png",
	"1. FC Köln": "https://tmssl.akamaized.net//images/wappen/small/3.png",
	"1. FC Nürnberg": "https://tmssl.akamaized.net//images/wappen/small/4.png",
	"1. FC Saarbrücken": "https://tmssl.akamaized.net//images/wappen/small/1.png",
	"1. FC Union Berlin": "https://tmssl.akamaized.net//images/wappen/small/89.png",
	"1. FSV Mainz 05": "https://tmssl.akamaized.net//images/wappen/small/39.png",
	"1860 München": "https://tmssl.akamaized.net//images/wappen/small/72.png",
	"Alemannia Aachen": "https://tmssl.akamaized.net//images/wappen/small/8.png",
	"Arminia Bielefeld": "https://tmssl.akamaized.net//images/wappen/small/10.png",
	"Bayer 04 Leverkusen": "https://tmssl.akamaized.net//images/wappen/small/15.png",
	"Bayer 05 Uerdingen": "https://tmssl.akamaized.net//images/wappen/small/95.png", // Same as KFC Uerdingen
	"Bayern München": "https://tmssl.akamaized.net//images/wappen/small/27.png",
	"Bor. Mönchengladbach": "https://tmssl.akamaized.net//images/wappen/small/18.png",
	"Borussia Dortmund": "https://tmssl.akamaized.net//images/wappen/small/16.png",
	"Borussia Neunkirchen": "https://tmssl.akamaized.net//images/wappen/small/328.png",
	"Eintracht Braunschweig": "https://tmssl.akamaized.net//images/wappen/small/23.png",
	"Eintracht Frankfurt": "https://tmssl.akamaized.net//images/wappen/small/24.png",
	"Energie Cottbus": "https://tmssl.akamaized.net//images/wappen/small/25.png",
	"FC 08 Homburg": "https://tmssl.akamaized.net//images/wappen/small/459.png",
	"FC Augsburg": "https://tmssl.akamaized.net//images/wappen/small/167.png",
	"FC Ingolstadt 04": "https://tmssl.akamaized.net//images/wappen/small/4795.png",
	"FC Schalke 04": "https://tmssl.akamaized.net//images/wappen/small/33.png",
	"FC St. Pauli": "https://tmssl.akamaized.net//images/wappen/small/35.png",
	"Fortuna Düsseldorf": "https://tmssl.akamaized.net//images/wappen/small/38.png",
	"Fortuna Köln": "https://tmssl.akamaized.net//images/wappen/small/92.png",
	"Hamburger SV": "https://tmssl.akamaized.net//images/wappen/small/41.png",
	"Hannover 96": "https://tmssl.akamaized.net//images/wappen/small/42.png",
	"Hansa Rostock": "https://tmssl.akamaized.net//images/wappen/small/30.png",
	"Hertha BSC": "https://tmssl.akamaized.net//images/wappen/small/44.png",
	"KFC Uerdingen 05": "https://tmssl.akamaized.net//images/wappen/small/95.png",
	"Karlsruher SC": "https://tmssl.akamaized.net//images/wappen/small/48.png",
	"Kickers Offenbach": "https://tmssl.akamaized.net//images/wappen/small/107.png",
	"MSV Duisburg": "https://tmssl.akamaized.net//images/wappen/small/52.png",
	"Meidericher SV": "https://tmssl.akamaized.net//images/wappen/small/52.png", // Same as MSV Duisburg
	"Preußen Münster": "https://tmssl.akamaized.net//images/wappen/small/91.png",
	"RB Leipzig": "https://tmssl.akamaized.net//images/wappen/small/23826.png",
	"Rot-Weiss Essen": "https://tmssl.akamaized.net//images/wappen/small/56.png",
	"Rot-Wei\u00df Oberhausen": "https://tmssl.akamaized.net//images/wappen/small/57.png",
	"SC Freiburg": "https://tmssl.akamaized.net//images/wappen/small/60.png",
	"SC Paderborn 07": "https://tmssl.akamaized.net//images/wappen/small/127.png",
	"SC Tasmania 1900 Berlin": "https://tmssl.akamaized.net//images/wappen/small/44396.png",
	"SG Wattenscheid 09": "https://tmssl.akamaized.net//images/wappen/small/97.png",
	"SSV Ulm 1846": "https://tmssl.akamaized.net//images/wappen/small/69.png",
	"SV Darmstadt 98": "https://tmssl.akamaized.net//images/wappen/small/105.png",
	"SpVgg Blau-Wei\u00df 90 Berlin": "https://tmssl.akamaized.net//images/wappen/small/2149.png",
	"SpVgg Greuther Fürth": "https://tmssl.akamaized.net//images/wappen/small/65.png",
	"SpVgg Unterhaching": "https://tmssl.akamaized.net//images/wappen/small/66.png",
	"Stuttgarter Kickers": "https://tmssl.akamaized.net//images/wappen/small/71.png",
	"TSG Hoffenheim": "https://tmssl.akamaized.net//images/wappen/small/533.png",
	"Tennis Borussia Berlin": "https://tmssl.akamaized.net//images/wappen/small/101.png",
	"VfB Leipzig": "https://tmssl.akamaized.net//images/wappen/small/497.png",
	"VfB Stuttgart": "https://tmssl.akamaized.net//images/wappen/small/79.png",
	"VfL Bochum": "https://tmssl.akamaized.net//images/wappen/small/80.png",
	"VfL Wolfsburg": "https://tmssl.akamaized.net//images/wappen/small/82.png",
	"Waldhof Mannheim": "https://tmssl.akamaized.net//images/wappen/small/85.png",
	"Werder Bremen": "https://tmssl.akamaized.net//images/wappen/small/86.png",
	"Wuppertaler SV": "https://tmssl.akamaized.net//images/wappen/small/299.png",
};
